module AirGalletMainMap(
  input         game_active,
  input  [22:0] cpu_addr,
  input  [2:0]  cpu_fc,
  input         cpu_as,
  input         cpu_rw,
  input         read_strobe,
  input         write_strobe,
  input         extra_rom_has_data,
  input         prog_rom_valid,
  input         dtack_reg,
  input         agallet_irq,
  input         unknown_irq,
  input         video_irq,
  input  [15:0] input1_data,
  input  [15:0] input0_data,
  input  [15:0] palette_data,
  input  [15:0] layer0_regs_data,
  input  [15:0] layer1_regs_data,
  input  [15:0] layer2_regs_data,
  input  [15:0] layer0_vram8_data,
  input  [15:0] layer1_vram8_data,
  input  [15:0] layer2_vram8_data,
  input  [15:0] sound_data,
  input         sound_reply_empty,
  input  [15:0] sprite_ram_data,
  input  [15:0] work_ram_data,
  input  [15:0] main_ram_data,
  input  [15:0] prog_rom_data,
  output [23:0] cpu_byte_addr,
  output        prog_rom_select,
  output        main_ram_select,
  output        sprite_ram_select,
  output        sound_flags_read,
  output        sound_read,
  output        sound_write,
  output        layer0_vram8_select,
  output        layer1_vram8_select,
  output        layer2_vram8_select,
  output        layer0_regs_select,
  output        layer1_regs_select,
  output        layer2_regs_select,
  output        input0_read,
  output        input1_read,
  output        eeprom_write,
  output        palette_select,
  output [14:0] palette_ram_addr,
  output        extra_rom_select,
  output        work_ram_select,
  output [14:0] work_ram_addr,
  output        prog_rom_ready,
  output        irq_read,
  output [1:0]  irq_word_offset,
  output        sprite_swap_write,
  output        sync_dtack,
  output        cycle,
  output        unmapped_cycle,
  output        prog_rom_read,
  output        work_ram_read,
  output        work_ram_write,
  output        main_ram_read,
  output        main_ram_write,
  output        sprite_ram_read,
  output        sprite_ram_write,
  output        layer0_vram8_read,
  output        layer1_vram8_read,
  output        layer2_vram8_read,
  output        layer0_vram8_write,
  output        layer1_vram8_write,
  output        layer2_vram8_write,
  output        layer0_regs_write,
  output        layer1_regs_write,
  output        layer2_regs_write,
  output        palette_read,
  output        palette_write,
  output        sprite_regs_write,
  output        cpu_space,
  output        open_bus_select,
  output        dtack,
  output        read_data_valid,
  output [15:0] read_data
);
  wire        input0Select;
  wire        input1Select;
  wire        eepromSelect;
  wire        irqSelect;
  wire        soundSelect;
  wire        progRomAccess;
  wire        knownSelect;
  wire        dataStrobe;
  wire        layer0RegsDataSelect;
  wire        layer1RegsDataSelect;
  wire        layer2RegsDataSelect;
  wire        layerRegsMirrorSelect;

  wire [15:0] irqBaseCause =
    16'h0003 ^ (video_irq ? 16'h0001 : 16'h0000) ^ (unknown_irq ? 16'h0002 : 16'h0000);
  wire [15:0] irqCause =
    irq_word_offset == 2'h0
      ? ((irqBaseCause & 16'hfffb) | (agallet_irq ? 16'h0000 : 16'h0004))
      : irqBaseCause;

  AirGalletMainDecoder decoder(
    .game_active         (game_active),
    .cpu_addr            (cpu_addr),
    .cpu_fc              (cpu_fc),
    .cpu_as              (cpu_as),
    .cpu_rw              (cpu_rw),
    .read_strobe         (read_strobe),
    .write_strobe        (write_strobe),
    .extra_rom_has_data  (extra_rom_has_data),
    .prog_rom_valid      (prog_rom_valid),
    .dtack_reg           (dtack_reg),
    .cpu_byte_addr       (cpu_byte_addr),
    .prog_rom_select     (prog_rom_select),
    .extra_rom_select    (extra_rom_select),
    .work_ram_select     (work_ram_select),
    .work_ram_addr       (work_ram_addr),
    .main_ram_select     (main_ram_select),
    .palette_select      (palette_select),
    .palette_ram_addr    (palette_ram_addr),
    .sprite_ram_select   (sprite_ram_select),
    .input0_select       (input0Select),
    .input1_select       (input1Select),
    .input0_read         (input0_read),
    .input1_read         (input1_read),
    .eeprom_select       (eepromSelect),
    .eeprom_write        (eeprom_write),
    .layer0_vram8_select (layer0_vram8_select),
    .layer1_vram8_select (layer1_vram8_select),
    .layer2_vram8_select (layer2_vram8_select),
    .layer0_regs_select  (layer0_regs_select),
    .layer1_regs_select  (layer1_regs_select),
    .layer2_regs_select  (layer2_regs_select),
    .layer0_regs_data_select (layer0RegsDataSelect),
    .layer1_regs_data_select (layer1RegsDataSelect),
    .layer2_regs_data_select (layer2RegsDataSelect),
    .layer_regs_mirror_select (layerRegsMirrorSelect),
    .sprite_regs_select  (),
    .irq_select          (irqSelect),
    .irq_read            (irq_read),
    .irq_word_offset     (irq_word_offset),
    .sound_select        (soundSelect),
    .sound_flags_read    (sound_flags_read),
    .sound_read          (sound_read),
    .sound_write         (sound_write),
    .sprite_swap_write   (sprite_swap_write),
    .prog_rom_access     (progRomAccess),
    .prog_rom_ready      (prog_rom_ready),
    .sync_dtack          (sync_dtack),
    .cycle               (cycle),
    .known_select        (knownSelect),
    .unmapped_cycle      (unmapped_cycle),
    .prog_rom_read       (prog_rom_read),
    .work_ram_read       (work_ram_read),
    .work_ram_write      (work_ram_write),
    .main_ram_read       (main_ram_read),
    .main_ram_write      (main_ram_write),
    .palette_read        (palette_read),
    .palette_write       (palette_write),
    .sprite_ram_read     (sprite_ram_read),
    .sprite_ram_write    (sprite_ram_write),
    .layer0_vram8_read   (layer0_vram8_read),
    .layer1_vram8_read   (layer1_vram8_read),
    .layer2_vram8_read   (layer2_vram8_read),
    .layer0_vram8_write  (layer0_vram8_write),
    .layer1_vram8_write  (layer1_vram8_write),
    .layer2_vram8_write  (layer2_vram8_write),
    .layer0_regs_write   (layer0_regs_write),
    .layer1_regs_write   (layer1_regs_write),
    .layer2_regs_write   (layer2_regs_write),
    .sprite_regs_write   (sprite_regs_write),
    .cpu_space           (cpu_space),
    .data_strobe         (dataStrobe),
    .open_bus_select     (open_bus_select),
    .dtack               (dtack)
  );

  AirGalletMainReadMux readMux(
    .input1_read         (input1_read),
    .input0_read         (input0_read),
    .palette_select      (palette_select),
    .layer0_regs_select  (layer0RegsDataSelect),
    .layer1_regs_select  (layer1RegsDataSelect),
    .layer2_regs_select  (layer2RegsDataSelect),
    .layer0_vram8_select (layer0_vram8_select),
    .layer1_vram8_select (layer1_vram8_select),
    .layer2_vram8_select (layer2_vram8_select),
    .sound_flags_read    (sound_flags_read),
    .sound_read          (sound_read),
    .irq_read            (irq_read),
    .sprite_ram_select   (sprite_ram_select),
    .work_ram_select     (work_ram_select),
    .main_ram_select     (main_ram_select),
    .extra_rom_has_data  (extra_rom_has_data),
    .extra_rom_read      (extra_rom_select & read_strobe),
    .prog_rom_ready      (prog_rom_ready),
    .open_bus_read       ((open_bus_select | layerRegsMirrorSelect) & read_strobe),
    .input1_data         (input1_data),
    .input0_data         (input0_data),
    .palette_data        (palette_data),
    .layer0_regs_data    (layer0_regs_data),
    .layer1_regs_data    (layer1_regs_data),
    .layer2_regs_data    (layer2_regs_data),
    .layer0_vram8_data   (layer0_vram8_data),
    .layer1_vram8_data   (layer1_vram8_data),
    .layer2_vram8_data   (layer2_vram8_data),
    .sound_flags_data    (sound_reply_empty ? 16'h0002 : 16'h0000),
    .sound_data          (sound_data),
    .irq_data            (irqCause),
    .sprite_ram_data     (sprite_ram_data),
    .work_ram_data       (work_ram_data),
    .main_ram_data       (main_ram_data),
    .prog_rom_data       (prog_rom_data),
    .valid               (read_data_valid),
    .data                (read_data)
  );
endmodule
