module LayerProcessor_1(
  input         clock,
  input         io_ctrl_enable,
  input  [1:0]  io_ctrl_format,
  input         io_ctrl_regs_tileSize,
  input         io_ctrl_regs_enable,
  input         io_ctrl_regs_flipX,
  input         io_ctrl_regs_flipY,
  input         io_ctrl_regs_rowScrollEnable,
  input         io_ctrl_regs_rowSelectEnable,
  input  [8:0]  io_ctrl_regs_scroll_x,
  input  [8:0]  io_ctrl_regs_scroll_y,
  output [11:0] io_ctrl_vram8x8_addr,
  input  [31:0] io_ctrl_vram8x8_dout,
  output [9:0]  io_ctrl_vram16x16_addr,
  input  [31:0] io_ctrl_vram16x16_dout,
  output [8:0]  io_ctrl_lineRam_addr,
  input  [31:0] io_ctrl_lineRam_dout,
  output        io_ctrl_tileRom_rd,
  output [31:0] io_ctrl_tileRom_addr,
  input  [63:0] io_ctrl_tileRom_dout,
  input         io_video_clockEnable,
  input  [8:0]  io_video_pos_x,
  input  [8:0]  io_video_pos_y,
  input         io_video_vBlank,
  input  [8:0]  io_video_regs_size_x,
  input  [8:0]  io_video_regs_size_y,
  input  [8:0]  io_spriteOffset_x,
  input  [8:0]  io_spriteOffset_y,
  output [1:0]  io_pen_priority,
  output [5:0]  io_pen_palette,
  output [7:0]  io_pen_color
);
  CaveLayerProcessor #(
    .LAYER_OFFSET_LARGE (5'h11),
    .LAYER_OFFSET_SMALL (5'h09)
  ) layer (
    .clock                         (clock),
    .io_ctrl_enable                (io_ctrl_enable),
    .io_ctrl_format                (io_ctrl_format),
    .io_ctrl_regs_tileSize         (io_ctrl_regs_tileSize),
    .io_ctrl_regs_enable           (io_ctrl_regs_enable),
    .io_ctrl_regs_flipX            (io_ctrl_regs_flipX),
    .io_ctrl_regs_flipY            (io_ctrl_regs_flipY),
    .io_ctrl_regs_rowScrollEnable  (io_ctrl_regs_rowScrollEnable),
    .io_ctrl_regs_rowSelectEnable  (io_ctrl_regs_rowSelectEnable),
    .io_ctrl_regs_scroll_x         (io_ctrl_regs_scroll_x),
    .io_ctrl_regs_scroll_y         (io_ctrl_regs_scroll_y),
    .io_ctrl_vram8x8_addr          (io_ctrl_vram8x8_addr),
    .io_ctrl_vram8x8_dout          (io_ctrl_vram8x8_dout),
    .io_ctrl_vram16x16_addr        (io_ctrl_vram16x16_addr),
    .io_ctrl_vram16x16_dout        (io_ctrl_vram16x16_dout),
    .io_ctrl_lineRam_addr          (io_ctrl_lineRam_addr),
    .io_ctrl_lineRam_dout          (io_ctrl_lineRam_dout),
    .io_ctrl_tileRom_rd            (io_ctrl_tileRom_rd),
    .io_ctrl_tileRom_addr          (io_ctrl_tileRom_addr),
    .io_ctrl_tileRom_dout          (io_ctrl_tileRom_dout),
    .io_video_clockEnable          (io_video_clockEnable),
    .io_video_pos_x                (io_video_pos_x),
    .io_video_pos_y                (io_video_pos_y),
    .io_video_vBlank               (io_video_vBlank),
    .io_video_regs_size_x          (io_video_regs_size_x),
    .io_video_regs_size_y          (io_video_regs_size_y),
    .io_spriteOffset_x             (io_spriteOffset_x),
    .io_spriteOffset_y             (io_spriteOffset_y),
    .io_pen_priority               (io_pen_priority),
    .io_pen_palette                (io_pen_palette),
    .io_pen_color                  (io_pen_color)
  );
endmodule
